<!DOCTYPE html>
<html>
    <head>
        <base href="<?php echo APP_ROOT;?>" >
        <meta charset="utf-8">
        <title>Agenda de Contatos</title>
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="<?php echo '/'.APP_ROOT;?>/public/assets/css/materialize.min.css"  media="screen,projection"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <style>
            body {
                display: flex !important;
                min-height: 100vh !important;
                flex-direction: column !important;
            }

            main {
                flex: 1 0 auto !important;
            }
        </style>
    </head>
    <body>
        <header>
            <nav class="nav-wrapper">
                <div class="container">
                <a id="logo-container" href="<?php echo '/'.APP_ROOT;?>/app/contato/" class="brand-logo">Agenda de Contatos</a>
                <?php if(isset($_SESSION["LOGADO"]) || !empty($_SESSION["LOGADO"])):?>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="<?php echo '/'.APP_ROOT;?>/app/contato/">Home</a></li>    
                        <li><a href="<?php echo '/'.APP_ROOT;?>/app/contato/cadContato">Novo Contato</a></li>    
                        <li><a href="<?php echo '/'.APP_ROOT;?>/app/contato/cadLote">Contatos em Lote</a></li>    
                        <li><a href="<?php echo '/'.APP_ROOT;?>/app/login/sair">Sair</a></li>    
                    </ul>
                    <ul id="nav-mobile" class="sidenav">
                        <li><a href="<?php echo '/'.APP_ROOT;?>/app/login/sair">Sair</a></li>
                    </ul>
                    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <?php endif ?>
                </div>
            </nav>
        </header>
        <main>
            <?php $this->render(); ?>
        </main>

        <footer class="page-footer teal">
            <div class="footer-copyright">
                <div class="container">
                Feito Por:  Diego de Lima Lopes(Vespertino), Marina Lopes(Vespertino), Gabriel Prietro(Vespertino)
                </div>
            </div>
        </footer>


    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="./public/assets/js/materialize.min.js"></script>
    <script src="./public/assets/js/init.js"></script>
    </body>
</html>