<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Agenda Virtual</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="./public/assets/css/materialize.min.css"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <style>
        body {
            display: flex !important;
            min-height: 100vh !important;
            flex-direction: column !important;
        }

        main {
            flex: 1 0 auto !important;
        }
    </style>
</head>

<body>
    <header>
        <nav class="nav-wrapper">
            <ul class="left hide-on-med-and-down">
                <li><a href="#">Criar Novo Contato</a></li>
                <li><a href="#">Ver Contatos</a></li>
            </ul>
            <a id="logo-container" href="#" class="brand-logo center"><?php echo "Logo" ?></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="#">Cadastro em Lote</a></li>
                <li><a href="#">Categorias</a></li>    
            </ul>

            <ul id="nav-mobile" class="sidenav">
                <li><a href="#">Criar Novo Contato</a></li>
                <li><a href="#">Ver Contatos</a></li>
                <li><a href="#">Cadastro em Lote</a></li>
                <li><a href="#">Categorias</a></li> 
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </nav>
    </header>
    <main>